# version: "3"

# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend

#   backend:
#     build: ./backend
#     ports:
#       - "5000:5000"



services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   